### ISSUE TITLE
VirtualSky is not reading json information when offline

### ISSUE THREAD

**Issue by Whiteeeey** [slowe/VirtualSky#100]
I am trying to get VirtualSky to run offline on my computer so that I can use it as an object picker for my astrophotography setup (Pilomar). I downloaded the code from github and tried to get it working but I only get basic functionality with basic stars. I have worked out that this is because it is not loading any data from the json files that are stored locally, so it is unable to get Cardinal points, constellation lines, help menu information, any labels for stars or planets and most importantly for what I am trying to do, information from locally stored json information. If you know why this might be the case I would be most grateful, as I am unable to find a solution.

**Comment by slowe** [comment]
I can't know exactly why because I don't have access to be able to debug. But I will suggest a first thing to check would be if your browser (you don't say which browser or which operating system you are using) is set up to block access to local files. It may be doing this by default in order to, understandably, stop someone's code accessing your local file system. However, that will also result in the sort of outcome you describe if it is blocked from loading JSON files. You could try looking in the web developer tools for your browser to see if it prints out any warnings/errors.

In the past I've noticed that Chrome, in particular, tends to be funnier about allowing use of files in the same directory (or subdirectories) than other browsers. Chrome does have a command line flag `--allow-file-access-from-files` but be careful using that.

**Comment by Whiteeeey** [comment]
Thanks, I am using chrome. I will try that. I know it must be something to do with accessing local files as the embed code and the example files work really well and VirtualSky is quite small, which is what I am looking for. Thanks for all your work. As I said I am trying to make a web controller for an automatic star tracker for astrophotography. The project is someone else's project called Pilomar, a raspberry pi controlled look alike of the Palomar observatory. It is a good project as it is but a web controller with a nice skymap would be a good addition for picking targets. Thanks again for your assistance.

**Comment by Whiteeeey** [comment]
I ran my local directory over a simple python webserver and it is working perfectly. Thanks again for your assistance.
