### ISSUE TITLE
Language fallback fails when enable constellationlabels

### ISSUE THREAD

**Issue by ir193** [slowe/VirtualSky#33]
When the language is not supported, it just returns. However, the labels constellation is not loaded. 

https://github.com/slowe/VirtualSky/blob/gh-pages/virtualsky.js#L971

To reproduce this error: http://virtualsky.lco.global/embed/index.html?constellationlabels=true&lang=zh-CN

**Comment by slowe** [comment]
We were trying to limit 404 errors caused by people's browsers asking for a language that didn't have a translation. I've changed the code so it knows if the request for a language was via the `lang` parameter in the query string (in which case it will try to load it) or from the browser's default language (in which case it will only load from the list of known translations).

Sorry for being so slow at fixing this.
