### ISSUE TITLE
iFrame Not Working

### ISSUE THREAD

**Issue by morettisf** [slowe/VirtualSky#34]
I've tried to access a simple iFrame but there's no response from your server?

**Comment by slowe** [comment]
@morettisf Can you let me know which server you mean? A URL would be helpful.

**Comment by morettisf** [comment]
Just referencing this page and your instructions for embedding an iFrame. The <iframe> tag example doesn't seem to work for me: http://virtualsky.lco.global/embed/custom.html

**Comment by slowe** [comment]
@morettisf The custom iframe page is hosted by LCO so it may have been that their server wasn't up. Does it still not work? Could you try changing the URL in the iframe embed code to point at http://slowe.github.io/VirtualSky/embed rather than https://virtualsky.lco.global/embed/ and see if that is any different?

**Comment by slowe** [comment]
As this was from nearly two years ago and there was no reply, I'll assume it was down to lco.global issues.
