### ISSUE TITLE
What License do you guys offer for this project?

### ISSUE THREAD

**Issue by astrocket** [slowe/VirtualSky#43]
Hi guys.

Greetings from software developer who is a big fan of Cosmos.
I am trying to build some web application showing constellation with some user interactions.
Then I found out this library with rich functions and really would love to use this.

What License policy do you guys have?
Thanks.

@slowe

**Comment by avianey** [comment]
any idea ? BSD, Apache-2, whatever ?

**Comment by slowe** [comment]
I didn't see the notifications for this and life has been getting in the way. Sorry.

I always hate this sort of question because I feel I need some kind of advanced degree in licensing to know the differences between the various types and never have the time to commit to that. Basically, if you credit [Las Cumbres Observatory](https://lco.global/)/Stuart Lowe (somewhere appropriate) and add a link to this github repo I'm pretty happy.
