### ISSUE TITLE
Color of constellation lines #50

### ISSUE THREAD

**Issue by andyermkv** [slowe/VirtualSky#50]
Hello! I urgently need the opportunity to change the color of the lines of the constellations and increase the number of circumferential lines in the galactic grid. I need the ability to rotate the projection in a polar form in 3D mode with the mouse.
Thank you in advance!

**Comment by slowe** [comment]
Hi andyermkv. Thanks for commenting. This is an open source project so you can edit the code to change things. The three things you want to do have varying difficulty to implement.

- [ ] change the color of the lines of the constellations - easy
- [ ] increase the number of circumferential lines in the galactic grid - easy
- [ ] rotate the projection in a polar form in 3D mode with the mouse - hard

The last one is tougher to do because the current polar projections use the fact they are very limited to make all the coordinate conversions much easier/quicker. It'd involve some thought.

**Comment by slowe** [comment]
@andyermkv Given the lack of response I'll mark this as closed for now.
