### ISSUE TITLE
Projection of VirtualSky does not match reality on nightsky

### ISSUE THREAD

**Issue by HPWever** [slowe/VirtualSky#56]
I use an AllSky camera to timelapse the nights (great software on github by Thomas Jacquin). On top of the image of the camera I plot the constellations and coordinates using VirtualSky. This looks awasome!
However the VirtualSky overlay does not exactly plot the stars where they actually are on the camera image. I tried using different projections, but none of them match (not polar not fisheye). I also modified all settings (files index.html; config.js; virtualsky.json; controller.js; allsky.css), but no matter how I shift/tilt/size I cannot get it to map accurately.
Does anyone have a solution or hint?

Some data:
My camera is a ZWO ASI120MC camera with a wide-angle lens. The diagonal field of view is 150 degrees; in pixels: width 1280 hight 960.

**Comment by slowe** [comment]
@HPWever The problem here is that none of the projections in VirtualSky match the mapping of your wide-angle lens (polar and fisheye projections both have 180 degree field-of-views). However, others have managed to get things roughly aligned on a 150 degree field-of-view allsky camera using `projection=fisheye` and then using CSS to offset and scale the Virtual Sky e.g. https://uhhpc.herts.ac.uk/skyexplorers/

**Comment by WirthmU** [comment]
I am using a 3.2 mm lens with a field of view (FOV) of 120°(H) on Raspberry Pi High Quality Camera. What would be the best projection format for the starmap overlay?

I have tried to use projection=fisheye but it seems that there is a maximum size of the outer circle which is possible.
