### ISSUE TITLE
Constellation lines weight

### ISSUE THREAD

**Issue by Varazdat108** [slowe/VirtualSky#75]
Hi, thanks for nice work, its really fantastic .... Tell me please how can I change a weight of constellation lines and how can I fill with any color or gradient or png a Galactic plane region on map, thanks

**Comment by slowe** [comment]
@Varazdat108 At the moment there is no option for changing the weight of the constellation lines. The second part of your question is much bigger because the Galactic plane region is not drawn as a single filled polygon because this is a 2D drawing so you'd see the whole polygon even when half of it is "behind" you. That is why it isn't currently filled.

**Comment by Varazdat108** [comment]
> @Varazdat108 At the moment there is no option for changing the weight of the constellation lines. The second part of your question is much bigger because the Galactic plane region is not drawn as a single filled polygon because this is a 2D drawing so you'd see the whole polygon even when half of it is "behind" you. That is why it isn't currently filled.

Thanks, have a great day
