### ISSUE TITLE
Can I use "city" instead of coordinates?

### ISSUE THREAD

**Issue by lexterror** [slowe/VirtualSky#76]
I would like to know if there's a way of setting the city without coordinates?

I noticed there was a "cities.txt" file...

Thank you!

**Comment by slowe** [comment]
@lexterror I'm not sure if you mean in the user interface or via code or both or something else. In the [embed version](https://slowe.github.io/VirtualSky/embed) you click on the coordinates to get a location option that lets you enter a place name. If you were asking about how to do this via code, view the source of that page and you'll see it uses `geo/virtualsky-geo.js` (with a `callback`) which then uses a bunch of files in the `geo` sub-directory in order to do a location lookup without the need for a server or remote service and without asking for one big lookup file.
