### ISSUE TITLE
LookUp service

### ISSUE THREAD

**Issue by leitmori** [slowe/VirtualSky#86]
Since the LookUp service has been suspended, is it possible to self-host it?
See https://github.com/thomasjacquin/allsky-website/issues/41#issuecomment-816176493

**Comment by thomasjacquin** [comment]
Hi Stuart,

First, let me say I am very sorry for putting a strain on your look up service. I only realized it now.
The culprit is a line on my website included to display "M42;M45;M31;M51;M81".

Over time, a few people have implemented my website but unfortunately, that line was included in the GitHub repo.
I just pushed a commit to remove the use of your look up service. https://github.com/thomasjacquin/allsky-website/commit/8807efd2b5e9a011bef7e805c61e02745ec64a1a

I will also reach out to the allsky community so they remove that line in their `virtualsky.json` configuration file.

Sorry for the trouble.

Thomas

**Comment by slowe** [comment]
@thomasjacquin Thanks for letting me know the source. Hopefully your change propagates. By the way, example 10 shows how you could show the Messier catalogue (or a sub-section of it) using a static json file e.g. https://slowe.github.io/VirtualSky/#ex10 That also reduces the number of requests in the browser so is faster for the user too.

@leitmori Unfortunately it isn't possible to self-host my code because it'd need too much work to make it more portable and, as I said, I just don't have the resources (time, mental) to do that; it has been a draining 14/15 months.

**Comment by leitmori** [comment]
Thank you both so much for your great work!

**Comment by thomasjacquin** [comment]
@slowe Thanks for pointing me to this example. This is actually what I intended to do from the beginning since I only wanted to display a few objects on the map but didn't need the extra information from the lookup service. I should have read the doc more thoroughly.
